model:
  l1_size: 1024
  l2_size: 8
  l3_size: 96
data:
  features: HalfKP
  train: ../train.bin
  val: ../train.bin
  smart_fen_skipping: true
  random_fen_skipping: 10
  batch_size: 16384
  num_workers: 8
  threads: 8
trainer:
  accelerator: gpu
  devices: 1